---
apiVersion: v1
kind: Pod
metadata:
    name: my-jenkins
    labels:
      author: Devendra
      type: jenkins
spec:
  containers:
    - name: my-jenkins-cont
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 8081
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: slave1
                values:
                  - myname
                operator: In

...