---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-affinity-dep
    labels:
      author: Devendra
      type: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      type: nginx
  template:
    metadata:
      name: my-nginx-pod
      labels:
        author: Devendra
        type: nginx
    spec:
      containers:
        - name: my-nginx-cont
          image: nginx

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
              - matchExpressions:
                 - key: label1
                   values:
                    - Devendra
                   operator: In
              - matchExpressions:
                  - key: label3
                    values:
                      - Devendra3
                    operator: In

...