---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  labels:
    creator: Devendra
    type: local-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

...