---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    creator: Devendra
    type: local-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/Data

...
