---
apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  labels:
    author: Devendra
    type: server
spec:
  containers:
    - name: myserver
      image: nginx
      volumeMounts:
        - name: myvolume
          mountPath: /usr/share/nginx/html

  volumes:
    - name: myvolume
      persistentVolumeClaim:
        claimName: mypvc

...