---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server
  labels:
    author: Devendra
    type: sql-server

spec:
  replicas: 2
  selector:
    matchLabels:
      type: sql-server
  template:

    metadata:
      name: sql-server-pod
      labels:
        author: Devendra
        type: sql-server
    spec:
      containers:
        - name: my-sql-server
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                SecretKeyRef:
                  name: mysql-secret
                  key: password


...