---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    author: Devendra
    type: server
spec:
  containers:
    - name: my-server
      image: tomee
      ports:
        - containerPort: 80
          hostPort: 8080

  tolerations:
    - key: slave2
      value: t2
      operator: Equal
      effect: NoSchedule

...