apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: my-redis
  name: my-redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: my-redis
    spec:
      containers:
      - image: redis
        name: my-redis
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
status: {}
